<?php

/**
 * @file
 * Provides some custom access.
 */

/**
 * Implements hook_permission().
 */
function mal_user_custom_access_permission() {
  return array(
    'edit school which was specified in profile' => array(
      'title' => t('Edit school which was specified in profile'),
    ),
    'access main administration page' => array(
      'title' => t('Access main administration page'),
      'description' => t('Limit access to /admin page.'),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function mal_user_custom_access_node_access($node, $op, $account) {
  if (($op == 'update')
    && (!empty($node->type))
    && ($node->type == 'school')
    && (user_access('edit school which was specified in profile'))
  ) {
    $user = entity_metadata_wrapper('user', $account);
    foreach ($user->field_user_school->value() as $school) {
      if ($school->nid == $node->nid) {
        return NODE_ACCESS_ALLOW;
      }
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_menu_alter().
 */
function mal_user_custom_access_menu_alter(&$items) {
  $items['admin']['access arguments'] = array('access main administration page');
}
