<?php
/**
 * @file
 * Fills "Updated by editor" field if node was updated manually.
 */

/**
 * Implements hook_node_presave().
 */
function mal_content_updated_manually_node_presave($node) {
  global $user;
  if (!empty($node->storefield)) {
    $node->changed = $node->storefield;
    unset($node->storefield);
  }
  if ($user->uid != 0) {
    $node->field_updated_by_editor[LANGUAGE_NONE][0]['value'] = $node->changed;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function mal_content_updated_manually_views_pre_render(&$view) {
  global $user;
  if ($view->name == 'view_admin_view_old' && in_array('Malmo middle admin', $user->roles)) {
    unset($view->field['changed']);
  }
}

/**
 * Implements hook_menu().
 */
function mal_content_updated_manually_menu() {
  $items = array();
  $items['admin/config/ffw/batch_content_update_manually'] = array(
    'title'           => 'Updated by editor batch',
    'description'     => 'Fill Updated by editor field',
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('batch_content_update_manually_form'),
    'access arguments'=> array('create users'),
    'access callback' => 'user_access',
  );

  return $items;
}

/**
 * Form builder function to allow choice of which batch to run.
 */
function batch_content_update_manually_form() {
  $form['description'] = array(
    '#type'   => 'markup',
    '#markup' => t('Batch grabs all nodes and fills "Updated by editor" field.<br>
                    It should be used just once to update current content.<br>'),
  );
  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Go'),
  );

  return $form;
}

/**
 * Submit handler.
 *
 * @param array $form
 *   Form API form.
 * @param array $form_state
 *   Form API form.
 */
function batch_content_update_manually_form_submit($form, &$form_state) {
  $batch = batch_content_update_manually_init();
  batch_set($batch);
}

/**
 * Custom batch init function.
 */
function batch_content_update_manually_init() {
  $operations = array();
  $nodes = node_load_multiple(array(), TRUE);
  foreach ($nodes as $node) {
    $operations[] = array(
      'batch_content_update_manually',
      array(
        $node
      ),
    );
  }
  $batch = array(
    'operations' => $operations,
    'finished'   => 'batch_content_update_manually_finished',
  );

  return $batch;
}

/**
 * Batch operation function.
 */
function batch_content_update_manually($node, &$context) {
  $node->storefield = $node->changed;
  if (empty($node->field_updated_by_editor)) {
    $node->field_updated_by_editor[LANGUAGE_NONE][0]['value'] = $node->storefield;
  }
  node_save($node);
}

/**
 * Batch finished function.
 */
function batch_content_update_manually_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message(t('Congratulations! All nodes were updated successfully'));
  }
}
