<?php

/**
 * @file
 * Modifications in user register logic.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function user_register_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_element_info_alter().
 *
 * Remove default user process, that adds client-side validation.
 */
function user_register_element_info_alter(&$type) {
  if (!empty($type['password_confirm'])) {
    $user_process_key = array_search('user_form_process_password_confirm', $type['password_confirm']['#process']);
    if ($user_process_key !== FALSE) {
      unset($type['password_confirm']['#process'][$user_process_key]);
    }
    $type['password_confirm']['#process'][] = 'user_register_process_password_confirm';
  }
}

/**
 * Form element process handler for tooltip on password fields.
 *
 * @param array $element
 *   Form API element of password_confirm type.
 *
 * @return array
 *   Modified element.
 */
function user_register_process_password_confirm($element) {
  $element['pass1']['#description']
    = $element['pass2']['#description']
      = $element['#description'];

  return $element;
}

/**
 * Implements hook_menu_alter().
 *
 * Restrict access to default register page.
 */
function user_register_menu_alter(&$items) {
  $items['user/register']['access callback'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter user login form and add link to restore the password.
 */
function user_register_form_user_login_alter(&$form, &$form_state) {
  $form['actions']['password'] = array(
    '#markup' => l(t('Request new password'), 'user/password', array('attributes' => array('class' => array('btn', 'btn-default')))),
  );
  $form['#submit'][] = 'user_register_form_user_login_form_submit';
}

/**
 * User login form submit callback.
 *
 * Redirect user to front page.
 */
function user_register_form_user_login_form_submit($form, &$form_state) {
  $form_state['redirect'] = '';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter user update password form and remove all unnecessary stuff.
 */
function user_register_form_user_profile_form_alter(&$form, $form_state) {
  $form['timezone']['#access'] = FALSE;
  $form['locale']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_register_form_registration_form_alter(&$form, &$form_state) {
  unset($form['who_message']);
  unset($form['actions']['cancel']);

  $id = drupal_html_id('edit-ajax-registration-submit');

  $form['#prefix'] = '<div id="user-register-form-wrapper-' . $form['#registration_settings']['entity_type'] . '-' . $form['#registration_settings']['entity_id'] . '" class="subscribe">';
  $form['#suffix'] = '</div>';
  $form['actions']['submit']['#ajax'] = array(
    'wrapper' => 'user-register-form-wrapper-' . $form['#registration_settings']['entity_type'] . '-' . $form['#registration_settings']['entity_id'],
    'callback' => 'user_register_unregistration_form_reload',
  );
  $form['actions']['submit']['#value'] = t('Register on course');
  $form['actions']['submit']['#id'] = $id;
  $form['actions']['submit']['#attributes']['id'][] = $id;
  $form['actions']['submit']['#attributes']['class'][] = 'btn-xs';
}

/**
 * Ajax form callback. Simply reload form.
 *
 * @param array $form
 *   Form renderable array.
 *
 * @return array
 *   Form renderable array.
 */
function user_register_unregistration_form_reload($form) {
  global $user;
  $registration = user_register_load_registration_by_user($form['#registration_settings']['entity_type'], $form['#registration_settings']['entity_id'], $user->uid);

  // Default commands set for form handling.
  $commands = array(
    '#type' => 'ajax',
    '#commands' => ajax_prepare_response(drupal_get_form('user_register_unregister_ajax_form', $registration)),
  );

  // Rebuild sidebar course menu content.
  $view = views_get_view('sidebar_courses');
  $view->set_arguments(array($user->uid));
  $sidebar_content = $view->render('course_menu_pane');

  $commands['#commands'][] = ajax_command_html('.courses-menu-block', $sidebar_content);

  return $commands;
}

/**
 * Ajax form callback. Simply reload form.
 *
 * @param array $form
 *   Form renderable array.
 *
 * @return array
 *   Form renderable array.
 */
function user_register_registration_form_reload($form) {
  $prev_registration = $form['registration']['#value'];
  global $user;

  $registration = entity_get_controller('registration')->create(array(
    'entity_type' => $prev_registration->entity_type,
    'entity_id' => $prev_registration->entity_id,
    'type' => $prev_registration->type,
  ));

  // Default commands set for form handling.
  $commands = array(
    '#type' => 'ajax',
    '#commands' => ajax_prepare_response(drupal_get_form('registration_form', $registration)),
  );

  // Rebuild sidebar course menu content.
  $view = views_get_view('sidebar_courses');
  $view->set_arguments(array($user->uid));
  $sidebar_content = $view->render('course_menu_pane');

  $commands['#commands'][] = ajax_command_html('.courses-menu-block', $sidebar_content);

  return $commands;
}

/**
 * Implements hook_field_formatter_info().
 */
function user_register_field_formatter_info() {
  return array(
    'toggling_registration_form' => array(
      'label' => t('Register and Unregister Form via ajax toggling'),
      'field types' => array('registration'),
    ),
    'unregister_form' => array(
      'label' => t('Unregister Form'),
      'field types' => array('registration'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function user_register_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  global $user;

  // We know we should only have a single item.
  if (isset($items[0]['registration_type']) && !empty($items[0]['registration_type'])) {
    $reg_type = registration_type_load($items[0]['registration_type']);
    list($entity_id) = entity_extract_ids($entity_type, $entity);

    if (!registration_status($entity_type, $entity_id) || !$reg_type) {
      return $element;
    }

    switch ($display['type']) {
      case 'toggling_registration_form':
        if (user_is_anonymous()) {
          $message = t('!login or !register to subscribe the course.', array(
            '!login' => l(t('Log in'), 'user'),
            '!register' => l(t('register'), 'register'),
          ));
          $element[0] = array(
            '#markup' => '<div class="subscribe-message">' . $message . '</div>',
          );
        }
        else {
          $registration = user_register_load_registration_by_user($entity_type, $entity_id, $user->uid);

          if (!$registration && registration_register_page_access($entity_type, $entity)) {
            $registration = entity_get_controller('registration')->create(array(
              'entity_type' => $entity_type,
              'entity_id' => $entity_id,
              'type' => $reg_type->name,
            ));
            $element[0] = drupal_get_form('registration_form', $registration);
          }

          if ($registration && entity_access('delete', 'registration', $registration)) {
            $registration = user_register_load_registration_by_user($entity_type, $entity_id, $user->uid);
            $element[0] = drupal_get_form('user_register_unregister_ajax_form', $registration);
          }
        }
        break;

      case 'unregister_form':
        $registration = user_register_load_registration_by_user($entity_type, $entity_id, $user->uid);
        if ($registration && entity_access('delete', 'registration', $registration)) {
          $registration = user_register_load_registration_by_user($entity_type, $entity_id, $user->uid);
          $element[0] = drupal_get_form('user_register_unregister_form_' . $registration->registration_id, $registration);
        }
        break;
    }
  }

  return $element;
}

/**
 * Load single registration instance for given node.
 *
 * @param string $entity_type
 *   Entity type registration is attached to.
 * @param string|int $entity_id
 *   Entity id registration os attached to.
 * @param string|int $uid
 *   Current user ID.
 *
 * @return bool|Registration
 *   False if no registration was found of found registration.
 */
function user_register_load_registration_by_user($entity_type, $entity_id, $uid) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'registration')
    ->propertyCondition('entity_id', $entity_id)
    ->propertyCondition('entity_type', $entity_type)
    ->propertyCondition('user_uid', $uid)
    ->execute();

  if (!empty($result['registration'])) {
    return registration_load(key($result['registration']));
  }

  return FALSE;
}

/**
 * Implements hook_forms().
 *
 * All user_register_unregister_form forms share the same form handler.
 */
function user_register_forms($form_id) {
  $forms = array();
  if (strpos($form_id, 'user_register_unregister_form_') === 0) {
    $forms[$form_id]['callback'] = 'user_register_unregister_form';
  }
  return $forms;
}

/**
 * User unregister form.
 *
 * @param array $form
 *   Renderable form array.
 * @param array $form_state
 *   Form state array.
 * @param Registration $registration
 *   Registration entity.
 *
 * @return array
 *   Renderable form array.
 */
function user_register_unregister_form($form, &$form_state, $registration) {
  if (!$registration) {
    return $form;
  }

  if (current_path() != 'system/ajax') {
    $form['#action'] = current_path();
  }
  elseif (!empty($_SERVER['HTTP_REFERER'])) {
    $url_info = parse_url($_SERVER['HTTP_REFERER']);
    $form['#action'] = $url_info['path'];
  }
  else {
    $form['#action'] = 'my-planning';
  }

  $form['registration'] = array(
    '#type' => 'value',
    '#value' => $registration,
  );

  $id = drupal_html_id('edit-registration-submit');

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unregister from course'),
    '#attributes' => array(
      'class' => array('btn-xs'),
      'id' => array($id),
    ),
    '#id' => $id,
  );

  $form['#prefix'] = '<div class="unsubscribe">';
  $form['#suffix'] = '</div>';

  return $form;
}

/**
 * User ajax unregister form.
 *
 * @param array $form
 *   Renderable form array.
 * @param array $form_state
 *   Form state array.
 * @param Registration $registration
 *   Registration entity.
 *
 * @return array
 *   Renderable form array.
 */
function user_register_unregister_ajax_form($form, &$form_state, $registration) {
  if (!$registration) {
    return $form;
  }

  $form['#submit'][] = 'user_register_unregister_form_submit';

  $form['registration'] = array(
    '#type' => 'value',
    '#value' => $registration,
  );

  $id = drupal_html_id('edit-ajax-registration-submit');

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unregister from course'),
    '#attributes' => array(
      'class' => array('btn-xs'),
      'id' => array($id),
    ),
    '#id' => $id,
  );

  $wrapper_id = 'user-register-form-wrapper-' . $registration->entity_type . '-' . $registration->entity_id;
  $form['#prefix'] = '<div id="' . $wrapper_id . '" class="unsubscribe">';
  $form['#suffix'] = '</div>';
  $form['actions']['submit']['#ajax'] = array(
    'wrapper' => $wrapper_id,
    'callback' => 'user_register_registration_form_reload',
  );

  return $form;
}

/**
 * Submit callback for user_register_unregister_ajax_form that unregister user.
 *
 * @param array $form
 *   Renderable form array.
 * @param array $form_state
 *   Form state array.
 */
function user_register_unregister_form_submit($form, &$form_state) {
  entity_delete('registration', $form_state['values']['registration']->registration_id);
}
