---

dependencies: []

galaxy_info:
  author: Maciej Delmanowski <drybjed@gmail.com>
  description: Ansible role to build and install Ansible .deb package
  company: ginas
  license: GPLv3
  min_ansible_version: 1.7.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - development
  - packaging
  - system

