---
- name: Clone Drush from GitHub.
  git: >
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush_install_path }}
    version={{ drush_version }}
    update={{ drush_keep_updated }}

- name: Install Drush dependencies with Composer.
  shell: >
    composer install --prefer-source --no-interaction
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php

- name: Create drush symlink.
  file: >
    src={{ drush_install_path }}/drush
    dest={{ drush_path }}
    state=link

- name: Run drush to finish setting it up.
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"

#- name: Reinstall Drupal
#  debug: msg="Profile dir = {{ drupal_profile_dir }}. Drupal branch = {{ drupal_branch }}. Drupal DB Url = {{ drupal_db_url }}"
#  shell: >
#    chdir={{ drupal_profile_dir }}
#    sh local.build_mal.sh {{ drupal_branch }} {{ drupal_db_url }}
