<?php

/**
 * @file
 * mal_search.module file.
 */

/**
 * Implements hook_entity_property_info_alter().
 */
function mal_search_entity_property_info_alter(&$info) {
  $info['node']['properties']['duration_days'] = array(
    'type' => 'list<text>',
    'label' => t('Duration days'),
    'bundle' => 'course',
    'schema field' => 'field_course_periods',
    'field' => TRUE,
    'sanitized' => TRUE,
    'getter callback' => 'mal_search_property_duration_days_getter_callback',
    // 'schema field' => 'language',
  );
  $info['node']['properties']['global_searchable'] = array(
    'type' => 'boolean',
    'label' => t('Global searchable'),
    'schema field' => 'field_course_searchable_type',
    'field' => TRUE,
    'sanitized' => TRUE,
    'computed' => TRUE,
    'getter callback' => 'mal_search_property_global_searchable_getter_callback',
  );
}

/**
 * Implements hook_facetapi_sort_info().
 */
function mal_search_facetapi_sort_info() {
  $sorts = array();

  $sorts['weeks'] = array(
    'label' => t('Weeks'),
    'callback' => 'mal_search_weeks',
    'description' => t('Sort by natural order of days of week'),
    'weight' => -50,
  );

  return $sorts;
}

/**
 * Sort callback.
 */
function mal_search_weeks(array $a, array $b) {
  // 1416610800 == Saturday.
  $a_timestamp = strtotime(mal_search_convert_days($a['#indexed_value']), 1416610800);
  $b_timestamp = strtotime(mal_search_convert_days($b['#indexed_value']), 1416610800);

  if ($a_timestamp == $b_timestamp) {
    return 0;
  }
  return ($a_timestamp < $b_timestamp) ? -1 : 1;
}

/**
 * Translate to english.
 */
function mal_search_convert_days($date_string) {
  return strtr(strtolower($date_string), array(
        'måndag' => 'Monday',
        'tisdag' => 'Tuesday',
        'onsdag' => 'Wednesday',
        'torsdag' => 'Thursday',
        'fredag' => 'Friday',
        'lördag' => 'Saturday',
        'söndag' => 'Sunday',
      ));
}

/**
 * Getter callback for global_searchable field.
 */
function mal_search_property_global_searchable_getter_callback($item, array $options, $name, $type, $info) {
  foreach (field_get_items($type, $item, 'field_course_searchable_type', $options['language']) as $delta => $term) {
    return in_array($term['tid'], array(
      variable_get('mal_generate_content_searchable_type_0', 74),
      variable_get('mal_generate_content_searchable_type_1', 75),
    ));
  }
}
/**
 * Getter callback for time field.
 *
 * It returns translated week days names.
 */
function mal_search_property_duration_days_getter_callback($item, array $options, $name, $type, $info) {
  $values = array();
  // @todo add more flex: not hard code field name and values
  // and swedish translation.
  $strings = array(
    'mon' => t('Monday'),
    'tue' => t('Tuesday'),
    'wed' => t('Wednesday'),
    'thu' => t('Thursday'),
    'fri' => t('Friday'),
  );

  if (!empty($item->field_course_periods)) {
    foreach (field_get_items($type, $item, 'field_course_periods', $options['language']) as $delta => $period) {
      foreach ($strings as $machine_day => $day) {
        if (!empty($period[$machine_day])) {
          $values[$machine_day] = $day;
        }
      }
    }
  }

  return $values;
}

/**
 * Alter the query before executing the query.
 *
 * @param view $view
 *   The view object about to be processed.
 * @param SearchApiViewsQuery $query
 *   The Search API Views query to be altered.
 *
 * @see hook_views_query_alter()
 */
function mal_search_search_api_views_query_alter(view &$view, SearchApiViewsQuery &$query) {
  $get_param = variable_get('search_date_filter_get_param', 'search-start-date');

  if ($view->name == 'search'
    && isset($_GET[$get_param])
    && $get_param = strtotime($_GET[$get_param])
  ) {
    $group_id = $query->set_where_group();
    $query->condition('field_course_date:value', $get_param, '>=', $group_id);
  }
}

/**
 * Capitalizes the first letter.
 */
function mal_search_facet_items_alter(&$build, &$settings) {
  if ($settings->facet == "duration_days") {
    foreach ($build as $key => $item) {
      $build[$key]["#markup"] = drupal_ucfirst($item["#markup"]);
    }
  }
  if ($settings->facet == "field_course_form:name") {
    foreach ($build as $key => $item) {
      if ($key == 'Flexkurs') {
        $build[$key]["#markup"] = 'Flex';
      }
      else {
        unset($build[$key]);
      }
    }
  }
  if ($settings->facet == "global_searchable") {
    foreach ($build as $key => $item) {
      if ($item['#indexed_value'] == 0) {
        unset($build[$key]);
      }
      if ($item['#indexed_value'] == 1) {
        $build[$key]['#markup'] = t('Show only searchable courses');
      }
    }
  }
}

/**
 * Implements hook_search_api_processor_info().
 */
function mal_search_search_api_processor_info() {
  $processors['mal_data_processor'] = array(
    'name' => t('Mal index data preprocessor'),
    'description' => t('Make vital modifications on generated index data.'),
    'class' => 'MalSearchApiDataProcessor',
  );

  return $processors;
}
