<?php

/**
 * @file
 * mal_search.module file.
 */

/**
 * Implements hook_entity_property_info_alter().
 */
function mal_search_entity_property_info_alter(&$info) {
  $info['node']['properties']['duration_days'] = array(
    'type' => 'list<text>',
    'label' => t('Duration days'),
    'bundle' => 'course',
    'schema field' => 'field_course_periods',
    'field' => TRUE,
    'sanitized' => TRUE,
    'getter callback' => 'mal_search_property_duration_days_getter_callback',
    // 'schema field' => 'language',
  );
}

/**
 * Getter callback for time field.
 *
 * It returns translated week days names.
 *
 * @param array $item
 *   Fieldable entity object.
 * @param array $options
 *   Option for particular get callback.
 * @param string $name
 *   Schema field name.
 * @param string $type
 *   Entity type.
 * @param array $info
 *   Structure from hook_entity_property_info().
 *
 * @return array
 *   Set of valid values for given field.
 */
function mal_search_property_duration_days_getter_callback($item, array $options, $name, $type, $info) {
  $values = array();
  // @todo add more flex: not hard code field name and values
  // and swedish translation.
  $strings = array(
    'mon' => t('Monday'),
    'tue' => t('Tuesday'),
    'wed' => t('Wednesday'),
    'thu' => t('Thursday'),
    'fri' => t('Friday'),
    'sat' => t('Saturday'),
    'sun' => t('SUnday'),
  );

  foreach (field_get_items($type, $item, $name, $options['language']) as $delta => $period) {
    foreach ($strings as $machine_day => $day) {
      if (!empty($period[$machine_day])) {
        $values[$machine_day] = $day;
      }
    }
  }

  return $values;
}
