<?php

/**
 * @file
 * Provides some custom access.
 */

/**
 * Implements hook_permission().
 */
function mal_user_custom_access_permission() {
  return array(
    'edit school which was specified in profile' => array(
      'title' => t('Edit school which was specified in profile'),
    ),
    'access main administration page' => array(
      'title' => t('Access main administration page'),
      'description' => t('Limit access to /admin page.'),
    ),
    'access configuration page' => array(
      'title' => t('Access configuration page'),
      'description' => t('Limit access to /admin/config page.'),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function mal_user_custom_access_node_access($node, $op, $account) {
  if (($op == 'update')
    && (!empty($node->type))
    && ($node->type == 'school')
    && (user_access('edit school which was specified in profile'))
  ) {
    $user = entity_metadata_wrapper('user', $account);
    if (!empty($user->field_user_school)) {
      foreach ($user->field_user_school->value() as $school) {
        if ($school->nid == $node->nid) {
          return NODE_ACCESS_ALLOW;
        }
      }
    }
  }

  // Editor should not edit courses and course-packages of schools that does
  // not specified in user's account.
  if (($op == 'update')
    && (!empty($node->type))
    && (in_array($node->type, array('course', 'course-packages')))
    && (in_array('School editor', array_values($account->roles)))
  ) {
    $user_wrapper = entity_metadata_wrapper('user', $account);
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $course_school = !empty($node_wrapper->field_course_school) ? $node_wrapper->field_course_school->value() : new stdClass();
    $result = NODE_ACCESS_DENY;

    if (!empty($user_wrapper->field_user_school)) {
      foreach ($user_wrapper->field_user_school->value() as $school) {
        if (!empty($course_school->nid) && $school->nid == $course_school->nid) {
          $result = NODE_ACCESS_ALLOW;
        }
      }
    }

    return $result;
  }

  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_menu_alter().
 */
function mal_user_custom_access_menu_alter(&$items) {
  $items['admin']['access arguments'] = array('access main administration page');
  $items['admin/config']['access arguments'] = array('access configuration page');
}
